modLoader="lowcodefml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="battlearmory_decocraft_cache"
version="1.7.2"
displayName="Battle Armory Decocraft Render Optimizer"
displayTest="IGNORE_ALL_VERSION"
description='''Client-side Battle Armory optimization for Decocraft and Decocraft Nature animated geometry, materials, transforms and render batching and shared BBModel parse graphs.'''

[[dependencies.battlearmory_decocraft_cache]]
modId="forge"
mandatory=true
versionRange="[47.4.20,48)"
ordering="NONE"
side="CLIENT"

[[dependencies.battlearmory_decocraft_cache]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.20.2)"
ordering="NONE"
side="CLIENT"

[[dependencies.battlearmory_decocraft_cache]]
modId="decocraft"
mandatory=true
versionRange="[3.0.4,4)"
ordering="AFTER"
side="CLIENT"
